version: "3.9"
services:
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - db
    TaskTrackerDb:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pass228228"
            ACCEPT_EULA: "Y"