name: TaskTracker CD

on:
  push:
    tags:
      - '*'
    
    
env:
  POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:

  deploy:
    if: github.event.base_ref == 'refs/heads/master'  # TODO: test it
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Container registry login
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    - name: Build and push
      run: heroku container:push web -a $APP_NAME --arg POSTGRES_CONNECTION_STRING="$POSTGRES_CONNECTION_STRING"

    - name: Deploy
      run: heroku container:release web -a $APP_NAME