name: TaskTracker CD

on:
  push:
    branches: [ dev ] #while debugging, after change to master
  pull_request:
    branches: [ master ]
    
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  SQLSERVER_CONNECTION_STRING: ${{ secrets.SQLSERVER_CONNECTION_STRING }}
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker login
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Build and push
      run: heroku container:push web -a $APP_NAME --arg DB_CONNECTION_STRING="${${{ secrets.SQLSERVER_CONNECTION_STRING }}}"

    - name: Deploy
      run: heroku container:release web -a $APP_NAME