name: TaskTracker CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]
    
env:
  SQLSERVER_HOSTNAME: ${{ secrets.SQLSERVER_HOSTNAME }}
  SQLSERVER_HOSTPORT: ${{ secrets.SQLSERVER_HOSTPORT }}
  SQLSERVER_LOGIN: ${{ secrets.SQLSERVER_LOGIN }}
  SQLSERVER_PASSWORD: ${{ secrets.SQLSERVER_PASSWORD }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker login
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Build and push
      run: heroku container:push web -a $APP_NAME --arg DB_HOSTNAME="$SQLSERVER_HOSTNAME",DB_HOSTPORT="$SQLSERVER_HOSTPORT",DB_LOGIN="$SQLSERVER_LOGIN",DB_PASSWORD="$SQLSERVER_PASSWORD"

    - name: Deploy
      run: heroku container:release web -a $APP_NAME